name: Lines of Code
on: [push]

jobs:
  line_counter:
    runs-on: ubuntu-latest
    name: Initialise
    steps:
      - name: Count The Lines
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: false
          directory: ./
          badge: .github/cloc.svg
          ignore: 'node_modules/|README'

      - name: Print the output
        run: |
          echo "Scanned: ${{ steps.badge.outputs.counted_files }}";
          echo "Line Count: ${{ steps.badge.outputs.total_lines }}";

