on: [push]
name: Run Test

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Launch the local action
        uses: ./ # Uses an action in the root directory
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./output/badge.svg
          ignore: 'node_modules/|README'

      - name: Print the output
        run: |
          echo "Scanned: ${{ steps.badge.outputs.counted_files }}";
          echo "Line Count: ${{ steps.badge.outputs.total_lines }}";
